[package]
name = "cyclonedx-windows-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wmi = "0.9.1"
winreg = "0.10"

[[bin]]
name = "cyclonedx-windows-generator"